name: Test workflows

on:
  workflow_dispatch:
    
  pull_request:
    branches:
      - master

jobs:
  connect-tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
