name: Test workflows

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  connect-tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@e870a1112fcc1faeeeeea3c1b0ce544e5ad01844
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          version: 1.28.0

      - name: Make a request
        shell: bash
        run: |
          curl http://10.96.116.82:1234/get
