name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var: [a, b]
    outputs:
      matrix-a: ${{ steps.set-matrix-a.outputs }}
      matrix-b: ${{ steps.set-matrix-b.outputs }}
    steps:
      - id: set-matrix-${{matrix.var}}
        run: |
          echo "::set-output name=${{ matrix.var }}::${{ matrix.var }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.job1.outputs.matrix }}"
